/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("PDTProposalObjectPageObjectPage journey");

        opaTest("Navigate to PDTProposalObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onThePDTProposalList.onFilterBar().iExecuteSearch();

            Then.onThePDTProposalList.onTable().iCheckRows();
            When.onThePDTProposalList.onTable().iPressRow(0);

            Then.onThePDTProposalObjectPage.iSeeThisPage();
        });


        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onThePDTProposalObjectPage.iCheckSection({ section: "GeneratedFacet1" });
            Then.onThePDTProposalObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "ProposalKey" });
            Then.onThePDTProposalObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Product" });
            Then.onThePDTProposalObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "ProductDescription" });
            Then.onThePDTProposalObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Plant" });
            Then.onThePDTProposalObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "StorageLocation" });
            Then.onThePDTProposalObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "MRPArea" });
            Then.onThePDTProposalObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "LevelType" });
            Then.onThePDTProposalObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "CurrentPDT" });
            Then.onThePDTProposalObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "ProposedPDT" });
            Then.onThePDTProposalObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Difference" });
            Then.onThePDTProposalObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "DeviationPercent" });
            Then.onThePDTProposalObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "POCount" });
            Then.onThePDTProposalObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "DateFrom" });
            Then.onThePDTProposalObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "DateTo" });
            Then.onThePDTProposalObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "UpdateRelevant" });
            Then.onThePDTProposalObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "UpdateStatus" });
            Then.onThePDTProposalObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "UpdateMessage" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});